services:
  pizzabot:
    image: wokkipannu/wokinpizza-twitter-bot-go:latest
    container_name: twitterbot
    restart: always
    volumes:
      - /opt/Twitterbot/.env:/twitterbot/.env
      - /opt/Twitterbot/message.json:/twitterbot/message.json
      - "/etc/localtime:/etc/localtime:ro"