name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd Wokinpizza-Twitter-Bot-Go
          git pull
          docker build -t wokkipannu/wokinpizza-twitter-bot-go:latest .
          docker-compose down
          docker-compose up -d